services:
  pgdb:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - cryptocurdb:/var/lib/postgresql/data

volumes:
  cryptocurdb:
